language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

install:
  - rm composer.lock
  - composer install

script:
  - vendor/bin/phpunit --whitelist=src --coverage-clover=coverage.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
